main_app/exam/routes.py
#   importing basic flask module
from flask import render_template
from flask import Blueprint
from flask import request
from flask import redirect
from flask import flash
from flask import url_for
from flask import jsonify

from main_app import db

from main_app.exam.forms import AddExamForm
from main_app.exam.forms import AddExamSubjectForm 
from main_app.exam.forms import AddStudentResultForm 

from main_app.models import Exam
from main_app.models import ExamSubject
from main_app.models import Student

#   initializing blueprint
exam = Blueprint('exam', __name__)


#   ADD EXAM 
@exam.route('/exam/add/', methods=['GET','POST'])
def addexam():
    form = AddExamForm()
    exams = Exam.query.all()
    if form.validate_on_submit():
        exam = Exam(exam_name=form.exam_name.data)
        db.session.add(exam)
        db.session.commit()
        flash('Exam added successfuylly ✔', 'success')
        return redirect(url_for('exam.addexam'))

    return render_template('exam/addexam.html', form=form, exams=exams)

@exam.route("/exam/<int:exam_id>/delete/", methods=['POST'])
def exam_delete(exam_id):
    exam = Exam.query.get_or_404(exam_id)
    db.session.delete(exam)
    db.session.commit()
    flash('Your post has been deleted! ✔', 'success')
    return redirect(url_for('exam.addexam'))   


#   ADD EXAM SUBJECT
@exam.route('/exam/subject/add/', methods=['GET', 'POST'])
def addexam_subject():
    form = AddExamSubjectForm()
    form.exam.choices = [(exam.id, exam.exam_name) for exam in Exam.query.all()]
    exam_subject = ExamSubject.query.all()
    if form.validate_on_submit():
        subject = ExamSubject(subject=form.exam_subject_name.data.lower(), full_marks=form.full_marks.data, pass_marks=form.pass_marks.data,exam_id=form.exam.data)
        db.session.add(subject)
        db.session.commit()
        flash('Exam Subject added successfuylly ✔', 'success')
        return redirect(url_for('exam.addexam_subject'))

    return render_template('exam/addexamSubject.html', form=form, exam_subject=exam_subject)


@exam.route("/exam/subject/<int:exam_id>/delete/", methods=['POST'])
def exam_subject_delete(exam_id):
    exam = ExamSubject.query.get_or_404(exam_id)
    db.session.delete(exam)
    db.session.commit()
    flash('Your post has been deleted! ✔', 'success')
    return redirect(url_for('exam.addexam_subject'))  


#   ADD STUDENT RESULT
@exam.route('/exam/student/result/', methods=['GET', 'POST'])
def addexam_student_result():
    # THIS METHOD IS NOT WORKING.
    # GOT A NEW IDEA

    # WE SHOULD ADD INDIVIDUAL SUBJECT MARK WITH STUDENT NAME AND ROLL 
    # AND SAVE INTO DATABASE, THEN WE CAN QUERY THEM BY SUBJECT AND MAKE A INDIVIDUAL STUDENT MARKSHEET 



    form = AddStudentResultForm()
    form.exam.choices = [(exam.id, exam.exam_name) for exam in Exam.query.all()]
    form.exam_subject_name.choices = [(examsubj.id, examsubj.subject) for examsubj in ExamSubject.query.all()]
    exam_subject = ExamSubject.query.all()
    totalsubject=7
    if form.validate_on_submit():
        print(f"Student name: {form.student_name.data}")
        print(f"Student Roll: {form.student_roll.data}")
        print(f"Student Class: {form.student_class.data}")
        print(f"Exam: {form.exam.data}")
        for subject in range(totalsubject):
            print(f"Exam subject name: {form.exam_subject_name.data}")
            print(f"Subject full marks: {form.full_marks.data}")
            print(f"Subject grade: {form.grade.data}")
            print(f"Subject Achive mark: {form.achive_mark.data}")
        print(f"Total mark: {form.total_marks.data}")
        print(f"Total achive mark: {form.total_achive_mark.data}")
        print(f"Total achive grade: {form.total_achive_grade.data}")
        print(f"Result note: {form.result_note.data}")
        # single_sub_array = []
        # for subject in range(totalsubject):
        #     subjectobj = {}
        #     subject['subject'] = 
            # subject['']=
            # exam_details = jsonify({'allsubjectresult': subjectArray})
        # subject = ExamSubject(exam_subject=form.exam_subject_name.data, full_marks=form.full_marks.data, pass_marks=form.pass_marks.data,exam_id=form.exam.data)
        # db.session.add(subject)
        # db.session.commit()
        flash('Exam Subject added successfuylly ✔', 'success')
        return redirect(url_for('exam.addexam'))

    return render_template('exam/addexamStudentResult.html', form=form, exam_subject=exam_subject, totalsubject=totalsubject)


@exam.route('/exam/subject/marks/<int:subject_id>/', methods=['GET', 'POST'])
def get_total_marks(subject_id):
    subjects = ExamSubject.query.filter_by(id=subject_id).all()
    subjectArray = []
    for subject in subjects:
        subobj = {}
        subobj['id'] = subject.id
        subobj['subject_name'] = subject.subject
        subobj['full_marks'] = subject.full_marks
        subobj['pass_marks'] = subject.pass_marks
        subjectArray.append(subobj)

    return jsonify({'subjects': subjectArray})

# ADD EXAM SUBJECT WISE RESULT
@exam.route('/exam/<int:exam_id>/<string:classname>/<string:subjectname>/result/create/', methods=['GET', 'POST'])
def addexam_subject_result(exam_id, classname, subjectname):
    exam = Exam.query.filter_by(id=exam_id).first()
    examsubject = ExamSubject.query.filter_by(subject=subjectname).first()
    students = Student.query.filter_by(classname=classname).all()
    return render_template('exam/addexamSubjectResult.html', classname=classname, students=students, examsubject=examsubject, exam=exam)

main_app/main/routes.py
#   importing basic flask module
from flask import render_template
from flask import Blueprint

#   initializing blueprint
main = Blueprint('main', __name__)

#   default route
@main.route('/')
def index():
    return render_template('index.html')

#   about route
@main.route('/about')
def about():
    return render_template('about.html', title='About Us')

main_app/templates/dashboard.html
{%  extends 'layout.html'  %}



{% block help_developer %}
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ >
# This Section help you to find specific section.

	0: head
		0.0: styles
		0.1: fonts


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
{% endblock %}



{% block body %}

  <div class="wrapper">

      <!-- Sidebar  -->
      <nav id="sidebar">

        <div class="sidebar-header">
            <h3>Dashboard</h3>
        </div>

        <ul class="list-unstyled components">
            <p>Dashboard</p>
            <li class="active">
                <a aria-expanded="false">
                    <i class="fa fa-home" aria-hidden="true"></i>
                    Home
                </a>
            </li>

            <li>
                <a
                  href="#teacherSubmenu"
                  data-toggle="collapse"
                  aria-expanded="false"
                  class="dropdown-toggle"
                >
                    <i class="fa fa-user" aria-hidden="true"></i>
                    Teacher
                </a>

                <ul class="collapse list-unstyled" id="teacherSubmenu">
                    <li>
                        <a href="#">view all</a>
                    </li>
                    <li>
                        <a href="#">add</a>
                    </li>
                    <li>
                        <a href="#">delete</a>
                    </li>
                </ul>
            </li>
            <li>
                <a
                  href="#pageSubmenu"
                  data-toggle="collapse"
                  aria-expanded="false"
                  class="dropdown-toggle"
                >
                    <i class="fa fa-graduation-cap" aria-hidden="true"></i>
                    Students
                </a>

                <ul class="collapse list-unstyled" id="pageSubmenu">
                    <li>
                        <a href="#">view all</a>
                    </li>
                    <li>
                        <a href="#">add</a>
                    </li>
                    <li>
                        <a href="#">delete</a>
                    </li>
                </ul>
            </li>
            <li>
                <a
                  href="#reportSubmenu"
                  data-toggle="collapse"
                  aria-expanded="false"
                  class="dropdown-toggle"
                >
                    <i class="fa fa-bug" aria-hidden="true"></i>
                    Report
                </a>

                <ul class="collapse list-unstyled" id="reportSubmenu">
                    <li>
                        <a href="#">view all</a>
                    </li>
                    <li>
                        <a href="#">add</a>
                    </li>
                    <li>
                        <a href="#">delete</a>
                    </li>
                </ul>

            </li>
        </ul>
      </nav>

      <script>
        const search = function (){
            console.log("Data has been enetered");
            const searchdata = document.getElementById('search-box').value;
            //console.log(searchdata,searchdata.length);
            if (searchdata.length > 15) {
                document.getElementById('search-icon').style="display:none;"
            } else {
                document.getElementById('search-icon').style="display:block;"
            }
        }
      </script>
      <!-- Page Content  -->
      <div id="content">
        <nav class="navbar navbar-expand-lg navbar-light bg-white">
          <div class="container-fluid" id="header">
            <input
              oninput="javascript:search()"
              type="text"
              name=""
              placeholder=""
              id="search-box"
              class="container-fluid"
            />
            <div class="class" id="search-icon">
              <a class="search-btn" href="#"
                ><i class="fa fa-search" aria-hidden="true"></i
              ></a>
            </div>
            <button type="button" id="sidebarCollapse" class="btn btn-info">
              <i class="fas fa-align-left"></i>
              <span></span>
            </button>
            <button
              class="btn btn-dark d-inline-block d-lg-none ml-auto"
              class="anything"
              type="button"
              data-toggle="collapse"
              data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <i class="fas fa-align-justify"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="nav navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link" id="log" href="#"
                    >Log Out <i class="fa fa-arrow-right" aria-hidden="true"></i
                  ></a>
                </li>
              </ul>
            </div>
          </div>
        </nav>

        <div class="card-deck" id="stats">
          <div class="row-md-10">
            <div class="card text-center">
              <div class="card-body">
                <h5 class="card-title">Students</h5>
                <p class="card-text" id="number">900</p>
              </div>
            </div>
          </div>
          <div class="row-md-10">
            <div class="card text-center">
              <div class="card-body">
                <h5 class="card-title">Reports</h5>
                <p class="card-text" id="number">90</p>
              </div>
            </div>
          </div>
          <div class="row-md-10">
            <div class="card text-center">
              <div class="card-body">
                <h5 class="card-title">Teacher</h5>
                <p class="card-text" id="number">1500</p>
              </div>
            </div>
          </div>
        </div>
        <br /><br />
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Students</th>
              <th scope="col">Reports</th>
              <th scope="col">Teachers</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="up">
                900 <i class="fa fa-arrow-up" aria-hidden="true"></i>
              </td>
              <td class="up">
                90 <i class="fa fa-arrow-up" aria-hidden="true"></i>
              </td>
              <td class="down">
                1500 <i class="fa fa-arrow-down" aria-hidden="true"></i>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <!-- Popper.JS -->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
      integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
      crossorigin="anonymous"
    ></script>
    <!-- Bootstrap JS -->
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
      integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
      crossorigin="anonymous"
    ></script>

    <script type="text/javascript">
      $(document).ready(function () {
          $('#sidebarCollapse').on('click', function () {
              $('#sidebar').toggleClass('active');
          });
      });
    </script>


{% endblock %}

main_app/templates/layout.html
{% extends 'layout.html' %}

{% block help_developer %}
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ >
# This Section help you to find specific section.

	0: head
		0.0: styles
		0.1: fonts


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
{% endblock %}



{% block body %}
<div class="custom_form_center_100vh">
    <div class="container text-center">
        <h1> All these routes are available </h1>

        <!--div class="btn-group btn-group-sm" role="group" aria-label="Small button group">
            <a href=" {{ url_for('main.index') }} " class="btn btn-outline-dark"> Home </a>
            <a href=" {{ url_for('users.login') }} " class="btn btn-outline-dark"> Login </a>
            <a href=" {{ url_for('users.login_parents') }} " class="btn btn-outline-dark"> Parents Login </a>
            <a href=" {{ url_for('users.admission') }} " class="btn btn-outline-dark"> Admission </a>
            <a href=" {{ url_for('users.apply_parents') }} " class="btn btn-outline-dark"> Parents Application Form </a>
            <a href=" {{ url_for('users.apply_teacher') }} " class="btn btn-outline-dark"> Teacher Application Form </a>
            <a href=" {{ url_for('main.about') }} " class="btn btn-outline-dark"> About </a>
        </div-->
        <div class="btn-group btn-group-sm mt-3" role="group" aria-label="Small button group">
            <a href=" {{ url_for('student.students') }} " class="btn btn-outline-dark">
                Add Student
            </a>
        </div>

        <br>

        <div class="btn-group btn-group-sm mt-3" role="group" aria-label="Small button group">
            <a href=" {{ url_for('exam.addexam') }} " class="btn btn-outline-dark">
                Add Exam
            </a>

            <a href=" {{ url_for('exam.addexam_subject') }} " class="btn btn-outline-dark">
                Add Exam Subject
            </a>
            <a href=" {{ url_for('exam.addexam_subject_result') }} " class="btn btn-outline-dark">
                Add Subjectwise Result
            </a>
            <a href=" {{ url_for('exam.addexam_student_result') }} " class="btn btn-outline-dark dislabled">
                Add Student Result
            </a>
        </div>
    </div>
</div>
{% endblock %}

main_app/templates/login.html
{% extends 'layout.html' %}

{% block additional_title %}
    Login -
{% endblock %}

{% block additional_link %}
    <!-- <link rel="stylesheet" href=" {{ url_for('static', filename='login/login.css') }} "> -->
{% endblock %}

{% block body %}
<main class="custom_form_center_100vh bg_gray">
    <section>
        <h1 class="text-center mb-5"> Login </h1>
        <form action="" method="post" class="form-small">
            {{ form.hidden_tag() }}

            <!-- email field -->
            <div class="mb-3">

                {{ form.email.label(class="form-label") }}

                {% if form.email.errors %}
                    {{ form.email( class="form-control is-invalid" ) }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>  {{ error }}   </span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(
                        class="form-control"
                    ) }}
                {% endif %}
            </div>

            <!-- password field -->
            <div class="mb-3">
                {{ form.password.label(class="form-label") }}
                
                {% if form.password.errors %}
                    {{ form.password( class="form-control is-invalid" ) }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>  {{ error }}   </span>
                        {% endfor %}
                    </div>

                {% else %}
                    {{ form.password(
                        class="form-control"
                    ) }}

                {% endif %}

            </div>

            <div class="form-check">
                {{ form.remember_me(class="form-check-input") }}
                {{ form.remember_me.label(class="form-check-label") }}
            </div>

            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                {{ form.login_button( class="btn btn-lg btn-primary" ) }}
            </div>

        </form>

    </section>

</main>
{% endblock %}

main_app/templates/register.html
{% extends 'layout.html' %}



{% block additional_title %}
    Login -
{% endblock %}



{% block additional_link %}
    <!-- <link rel="stylesheet" href=" {{ url_for('static', filename='login/login.css') }} "> -->
{% endblock %}



{% block body %}


    <main class="custom_form_center_100vh bg_gray">

        <section>

            <h1 class="text-center mb-5"> Demo Register for Check Login Auth </h2>

            <form action="" method="post" class="form-small">
                {{ form.hidden_tag() }}

                <!-- username field -->
                <div class="mb-3">

                    {{ form.username.label(class="form-label") }}

                    {% if form.username.errors %}
                        {{ form.username( class="form-control is-invalid" ) }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>  {{ error }}   </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control") }}
                    {% endif %}

                </div>

                <!-- email field -->
                <div class="mb-3">

                    {{ form.email.label(class="form-label") }}

                    {% if form.email.errors %}
                        {{ form.email( class="form-control is-invalid" ) }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>  {{ error }}   </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control") }}
                    {% endif %}

                </div>

                <!-- password field -->
                <div class="mb-3">

                    {{ form.password.label(class="form-label") }}

                    {% if form.password.errors %}
                        {{ form.password( class="form-control is-invalid" ) }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>  {{ error }}   </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control") }}
                    {% endif %}

                </div>


                <!-- confirm password field -->
                <div class="mb-3">

                    {{ form.confirm_password.label(class="form-label") }}

                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password( class="form-control is-invalid" ) }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>  {{ error }}   </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control") }}
                    {% endif %}

                </div>

                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    {{ form.reg_button( class="btn btn-lg btn-primary" ) }}
                </div>

            </form>

        </section>

    </main>
{% endblock %}